# Generated by Django 4.1.1 on 2023-01-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('create_user', models.CharField(max_length=50, verbose_name='кем создан')),
                ('change_date', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('change_user', models.CharField(max_length=50, verbose_name='кем изменен')),
            ],
        ),
    ]
