# Generated by Django 4.1.1 on 2023-01-07 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tasks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abstracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('abstractmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='abstracts.abstractmodel')),
                ('state', models.SmallIntegerField(choices=[(0, 'Новое задание'), (1, 'На исполнении'), (2, 'Исполнено')], default=0, verbose_name='состояние')),
                ('title', models.CharField(max_length=50, verbose_name='наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('is_all_day', models.BooleanField(default=False, verbose_name='на целый день')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='дата начало')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='дата конец')),
                ('repeat_type', models.SmallIntegerField(choices=[(0, 'Не повторять'), (1, 'Ежедневно'), (2, 'Еженедельно'), (3, 'Ежемесячно'), (4, 'Ежегодно')], verbose_name='повторять')),
            ],
            options={
                'verbose_name': 'задание',
                'verbose_name_plural': 'задания',
                'ordering': ['-change_date'],
            },
            bases=('abstracts.abstractmodel',),
        ),
        migrations.CreateModel(
            name='RepeatOver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeat', models.SmallIntegerField(verbose_name='повторять')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repeat_over', to='tasks.task')),
            ],
            options={
                'verbose_name': 'повторение',
                'verbose_name_plural': 'повторения',
            },
        ),
        migrations.CreateModel(
            name='PerfomanceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execute_date', models.DateTimeField(blank=True, null=True, verbose_name='дата исполнения')),
                ('comment', models.TextField(blank=True, max_length=500, null=True, verbose_name='Примечание')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='исполнитель')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task', verbose_name='задание')),
            ],
            options={
                'verbose_name': 'сведение об исполнении',
                'verbose_name_plural': 'сведения об исполнении',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='наименование')),
                ('file', models.FilePathField(path=tasks.models.file_path)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task', verbose_name='задание')),
            ],
            options={
                'verbose_name': 'файл',
                'verbose_name_plural': 'файлы',
            },
        ),
    ]
