# Generated by Django 4.1.1 on 2023-01-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='день рождения'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='подразделение'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='job',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='должность'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='management',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='организация'),
        ),
    ]
